export const REPLACEMENT_FUNCTIONALITY_PROPERTIES = [
  {
    ID: 'emulsionAbility',
    Functionality: [211],
    FunctionalityName: ['emulsifier'],
    DbName: 'emulsion_ability',
    Label: 'Emulsion Ability',
    Type: 'decimalNegativePositive',
    Unit: '%',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'emulsionStability',
    Functionality: [211, 214],
    FunctionalityName: ['emulsifier', 'stabilizer'],
    DbName: 'emulsion_stability',
    Label: 'Emulsion Stability',
    Type: 'decimalNegativePositive',
    Unit: '%',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'waterHoldingCapacity',
    Functionality: [214, 217, 220],
    FunctionalityName: ['stabilizer', 'thickener', 'bulking agent'],
    DbName: 'water_holding_capacity',
    Label: 'Water Holding Capacity',
    Type: 'decimalNegativePositive',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'ph',
    Functionality: [211, 214, 215, 223, 213, 228, 236, 218],
    FunctionalityName: [
      'emulsifier',
      'stabilizer',
      'antioxidant',
      'acidity regulator',
      'sweetener',
      'humectant',
      'color',
      'flavour enhancer',
    ],
    DbName: 'ph_maximum_concentration',
    Label: 'pH',
    Type: 'decimalNegativePositive',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'hlb',
    Functionality: [211],
    FunctionalityName: ['emulsifier'],
    DbName: 'hlb',
    Label: 'HLB',
    Type: 'number',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'freezingPoint',
    Functionality: [211, 214, 215, 223, 217, 220, 213],
    FunctionalityName: [
      'emulsifier',
      'stabilizer',
      'antioxidant',
      'acidity regulator',
      'thickener',
      'bulking agent',
      'sweetener',
    ],
    DbName: 'melting_freezing_point',
    Label: 'Freezing Point',
    Type: 'decimalNegativePositive',
    Unit: 'Degree C',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'zetaPotential',
    Functionality: [211],
    FunctionalityName: ['emulsifier'],
    DbName: 'zeta_potential',
    Label: 'Zeta Potential',
    Type: 'decimalNegativePositive',
    Unit: 'mV',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'titrableAcidity',
    Functionality: [223],
    FunctionalityName: ['acidity regulator'],
    DbName: 'titrable_acidity',
    Label: 'Titrable acidity',
    Type: 'text',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'antioxidantActivity',
    Functionality: [215],
    FunctionalityName: ['antioxidant'],
    DbName: 'antioxidant_acitivity',
    Label: 'Antioxidant activity',
    Type: 'text',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'viscosity',
    Functionality: [217, 220],
    FunctionalityName: ['thickener', 'bulking agent'],
    DbName: 'viscosity',
    Label: 'Viscosity',
    Type: 'decimalNegativePositive',
    Unit: 'Cp/mPa.s',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'oilHoldingCapacity',
    Functionality: [217],
    FunctionalityName: ['thickener'],
    DbName: 'oil_holding_capacity',
    Label: 'OHC',
    Type: 'decimalNegativePositive',
    Unit: '%',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'relativeSweetness',
    Functionality: [213],
    FunctionalityName: ['sweetener'],
    DbName: 'relative_sweetness',
    Label: 'Relative Sweetness',
    Type: 'decimalNegativePositive',
    Unit: 'DE',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'glycemicIndex',
    Functionality: [213],
    FunctionalityName: ['sweetener'],
    DbName: 'glycemic_index',
    Label: 'Glycemic Index',
    Type: 'decimalNegativePositive',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
  {
    ID: 'moisture',
    Functionality: [228, 236, 218],
    FunctionalityName: ['humectant', 'color', 'flavour enhancer'],
    DbName: 'moisture',
    Label: 'Moisture Content',
    Type: 'text',
    Unit: '',
    ReadOnly: false,
    Required: false,
  },
];
