export const PLANT_PROPERTY = [
    {
        ID: 'meltingFreezingPoint',
        DbName: 'melting_freezing_point',
        DbTable: "plants_physicochemical_properties",
        Label: 'Melting Freezing Point (degree C)',
    },
    {
        ID: 'boilingPoint',
        DbName: 'boiling_point',
        DbTable: "plants_physicochemical_properties",
        Label: 'Boiling Point (degree C)',
    },
    {
        ID: 'phMaximumConcentration',
        DbName: 'ph_maximum_concentration',
        DbTable: "plants_physicochemical_properties",
        Label: 'Ph Maximum Concentration',
    },
    {
        ID: 'moisture',
        DbName: 'moisture',
        DbTable: "plants_physicochemical_properties",
        Label: 'Moisture (%)',
    },
    {
        ID: 'porosity',
        DbName: 'porosity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Porosity (%)',
    },
    {
        ID: 'density',
        DbName: 'density',
        DbTable: "plants_physicochemical_properties",
        Label: 'Density (g/L)',
    },
    {
        ID: 'flammability',
        DbName: 'flammability',
        DbTable: "plants_physicochemical_properties",
        Label: 'Flammability',
    },
    {
        ID: 'thermalStability',
        DbName: 'thermal_stability',
        DbTable: "plants_physicochemical_properties",
        Label: 'Thermal Stability',
    },
    {
        ID: 'viscosity',
        DbName: 'viscosity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Viscosity (cp)',
    },
    {
        ID: 'crystallization',
        DbName: 'crystallization',
        DbTable: "plants_physicochemical_properties",
        Label: 'Crystallization',
    },
    {
        ID: 'adhesiveStrength',
        DbName: 'adhesive_strength',
        DbTable: "plants_physicochemical_properties",
        Label: 'Adhesive Strength',
    },
    {
        ID: 'cohesiveStrength',
        DbName: 'cohesive_strength',
        DbTable: "plants_physicochemical_properties",
        Label: 'Cohesive Strength',
    },
    {
        ID: 'micMlcMicrobial',
        DbName: 'mic_mlc_microbial',
        DbTable: "plants_physicochemical_properties",
        Label: 'Mic Mlc Microbial',
    },
    {
        ID: 'compressiveStrength',
        DbName: 'compressive_strength',
        DbTable: "plants_physicochemical_properties",
        Label: 'Compressive Strength',
    },
    {
        ID: 'tensileStrength',
        DbName: 'tensile_strength',
        DbTable: "plants_physicochemical_properties",
        Label: 'Tensile Strength',
    },
    {
        ID: 'shearResistance',
        DbName: 'shear_resistance',
        DbTable: "plants_physicochemical_properties",
        Label: 'Shear Resistance',
    },
    {
        ID: 'impact',
        DbName: 'impact',
        DbTable: "plants_physicochemical_properties",
        Label: 'Impact',
    },
    {
        ID: 'antioxidant_acitivity',
        DbName: 'antioxidant_acitivity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Antioxidant Acitivity',
    },
    {
        ID: 'emulsion_stability',
        DbName: 'emulsion_stability',
        DbTable: "plants_physicochemical_properties",
        Label: 'Emulsion Stability (%)',
    },
    {
        ID: 'emulsion_ability',
        DbName: 'emulsion_ability',
        DbTable: "plants_physicochemical_properties",
        Label: 'Emulsion ability (%)',
    },
    {
        ID: 'foam_ability',
        DbName: 'foam_ability',
        DbTable: "plants_physicochemical_properties",
        Label: 'Foam Stability (%)',
    },
    {
        ID: 'foam_capacity',
        DbName: 'foam_capacity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Foam Capacity (%)',
    },
    {
        ID: 'water_holding_capacity',
        DbName: 'water_holding_capacity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Water Holding Capacity (%)',
    },
    {
        ID: 'oil_holding_capacity',
        DbName: 'oil_holding_capacity',
        DbTable: "plants_physicochemical_properties",
        Label: 'Oil Holding Capacity (%)',
    },
    {
        ID: 'least_gelation_concentration',
        DbName: 'least_gelation_concentration',
        DbTable: "plants_physicochemical_properties",
        Label: 'Least Gelation Concentration (%)',
    },
    {
        ID: 'others',
        DbName: 'others',
        DbTable: "plants_physicochemical_properties",
        Label: 'Others',
    },
    {
        ID: 'zetaPotential',
        DbName: 'zeta_potential',
        Label: 'Zeta Potential',
        Type: 'decimalNegativePositive',
    },
    {
        ID: 'formShapeSize',
        DbName: 'form_shape_size',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Form Shape Size',
    },
    {
        ID: 'tastePurgeTrap',
        DbName: 'taste_purge_trap',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Taste Purge Trap',
    },
    {
        ID: 'smell',
        DbName: 'smell',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Smell',
    },
    {
        ID: 'colorAppearance',
        DbName: 'color_appearance',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Color Appearance',
    },
    {
        ID: 'juiciness',
        DbName: 'juiciness',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Juiciness (0-5)',
    },
    {
        ID: 'greasiness',
        DbName: 'greasiness (0-5)',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Greasiness',
    },
    {
        ID: 'texture',
        DbName: 'texture',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Texture',
    },
    {
        ID: 'hardness',
        DbName: 'hardness',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Hardness (0-5)',
    },
    {
        ID: 'plasticity',
        DbName: 'plasticity',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Plasticity',
    },
    {
        ID: 'elasticity',
        DbName: 'elasticity',
        DbTable: "plants_organoleptic_sensory_properties",
        Label: 'Elasticity',
    },
    {
        ID: 'calories',
        DbName: 'calories',
        DbTable: "plants_nutrional_properties",
        Label: 'Calories  (Kcal/100G)',
    },
    {
        ID: 'proteins',
        DbName: 'proteins',
        DbTable: "plants_nutrional_properties",
        Label: 'Proteins (g/100G)',
    },
    {
        ID: 'netCarbohydrates',
        DbName: 'net_carbohydrates',
        DbTable: "plants_nutrional_properties",
        Label: 'Net Carbohydrates (g/100G)',
    },
    {
        ID: 'freeSugars',
        DbName: 'free_sugars',
        DbTable: "plants_nutrional_properties",
        Label: 'Free Sugars (g/100G)',
    },
    {
        ID: 'sodium',
        DbName: 'sodium',
        DbTable: "plants_nutrional_properties",
        Label: 'Sodium (mg/100G)',
    },
    {
        ID: 'totalFats',
        DbName: 'total_fats',
        DbTable: "plants_nutrional_properties",
        Label: 'Total Fats (g/100G)',
    },
    {
        ID: 'saturatedFats',
        DbName: 'saturated_fats',
        DbTable: "plants_nutrional_properties",
        Label: 'Saturated Fats (g/100G)',
    },
    {
        ID: 'monoInsaturatedFats',
        DbName: 'mono_insaturated_fats',
        DbTable: "plants_nutrional_properties",
        Label: 'Mono Unsaturated Fats (g/100G)',
    },
    {
        ID: 'polyInsaturatedFats',
        DbName: 'poly_insaturated_fats',
        DbTable: "plants_nutrional_properties",
        Label: 'Poly Unsaturated Fats (g/100G)',
    },
    {
        ID: 'transFats',
        DbName: 'trans_fats',
        DbTable: "plants_nutrional_properties",
        Label: 'Trans Fats (g/100G)',
    },
    {
        ID: 'cholesterol',
        DbName: 'cholesterol',
        DbTable: "plants_nutrional_properties",
        Label: 'Cholesterol (g/100G)',
    },
    {
        ID: 'totalFiber',
        DbName: 'total_fiber',
        DbTable: "plants_nutrional_properties",
        Label: 'Total Fiber (g/100G)',
    },
    {
        ID: 'solubleFiber',
        DbName: 'soluble_fiber',
        DbTable: "plants_nutrional_properties",
        Label: 'Soluble Fiber (g/100G)',
    },
    {
        ID: 'insolubleFiber',
        DbName: 'insoluble_fiber',
        DbTable: "plants_nutrional_properties",
        Label: 'Insoluble Fiber (g/100G)',
    },
    {
        ID: 'vitamins',
        DbName: 'vitamins',
        DbTable: "plants_nutrional_properties",
        Label: 'Vitamins',
    },
    {
        ID: 'minerals',
        DbName: 'minerals',
        DbTable: "plants_nutrional_properties",
        Label: 'Minerals',
    },
    {
        ID: 'zoneAvailability',
        DbName: 'zone_availability',
        DbTable: "plants_sustainabilities",
        Label: 'Zone Availability',
    },
    {
        ID: 'landConsumption',
        DbName: 'land_consumption',
        DbTable: "plants_sustainabilities",
        Label: 'Land Consumption (Hectare)',
    },
    {
        ID: 'waterConsumption',
        DbName: 'water_consumption',
        DbTable: "plants_sustainabilities",
        Label: 'Water Consumption (Litre)',
    },
    {
        ID: 'energyConsumption',
        DbName: 'energy_consumption',
        DbTable: "plants_sustainabilities",
        Label: 'Energy Consumption',
    },
    {
        ID: 'timeConsumption',
        DbName: 'time_consumption',
        DbTable: "plants_sustainabilities",
        Label: 'Time Consumption (Months)',
    },
    {
        ID: 'carbonFootprint',
        DbName: 'carbon_footprint',
        DbTable: "plants_sustainabilities",
        Label: 'Carbon Footprint',
    },
    {
        ID: 'socialConcerns',
        DbName: 'social_concerns',
        DbTable: "plants_sustainabilities",
        Label: 'Social Concerns',
    },
    {
        ID: 'socialConcernsExplanation',
        DbName: 'social_concerns_explanation',
        DbTable: "plants_sustainabilities",
        Label: 'Social Concerns Explanation',
    },
    {
        ID: 'SourcesOfInfo',
        DbName: 'Sources_of_info',
        DbTable: "plants_sustainabilities",
        Label: 'Sources Of Information',
    },
    {
        ID: 'rasa',
        DbName: 'rasa',
        DbTable: "plants_ayurvedas",
        Label: 'Rasa',
    },
    {
        ID: 'guna',
        DbName: 'guna',
        DbTable: "plants_ayurvedas",
        Label: 'Guna',
    },
    {
        ID: 'dosha',
        DbName: 'dosha',
        DbTable: "plants_ayurvedas",
        Label: 'Dosha',
    },
    {
        ID: 'panchabuta',
        DbName: 'panchabuta',
        DbTable: "plants_ayurvedas",
        Label: 'Panchabuta',
    },
    {
        ID: 'temperature',
        DbName: 'temperature',
        DbTable: "plants_ayurvedas",
        Label: 'Temperature',
    },
    {
        ID: 'toxicity',
        DbName: 'toxicity',
        DbTable: "plants_toxicologies",
        Label: 'Toxicity',
    },
    {
        ID: 'healthRelatedConcern',
        DbName: 'health_related_concern',
        DbTable: "plants_toxicologies",
        Label: 'Health Related Concern',
    },
    {
        ID: 'explanation',
        DbName: 'explanation',
        DbTable: "plants_toxicologies",
        Label: 'Explanation',
    },
];

